services:
  eventize-dev:
    build:
      context: ./src/be
      dockerfile: Dockerfile.dev
    volumes:
      - './src/be:/workspace'
      - eventize-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true
  fe-dev:
    build:
      context: ./src/fe
      dockerfile: Dockerfile.dev
    volumes:
      - './src/fe:/workspace'
      - fe-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true

  postgres:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 12345678

volumes:
  eventize-dev-vsc:
  fe-dev-vsc: