services:
  eventize-dev:
    build:
      context: ./src/be
      dockerfile: Dockerfile.dev
    volumes:
      - './src/be:/workspace'
      - eventize-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true
  fe-dev:
    build:
      context: ./src/fe
      dockerfile: Dockerfile.dev
    volumes:
      - './src/fe:/workspace'
      - fe-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true

volumes:
  eventize-dev-vsc:
  fe-dev-vsc: