services:
  eventize-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    privileged: true
    volumes:
      - './:/workspace'
      - './scripts/entrypoint.sh:/entrypoint'
      - eventize-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - 3284:8080

volumes:
  eventize-dev-vsc:
